version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: olgau/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    image: olgau/foodgram_frontend
    volumes:
      - static:/static
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    env_file: .env
    ports:
      - 8000:80  
    volumes:
      - static:/static
      - media:/media