# Generated by Django 4.2.4 on 2023-08-29 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_favorited_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Введите правильный цвет в формате HEX (например, #RRGGBB).', 'invalid_color')], verbose_name='Цвет в HEX'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$', 'Введите правильное имя.', 'invalid')], verbose_name='Тег'),
        ),
    ]
