# Generated by Django 4.2.4 on 2023-08-29 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_tag_color_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[\\w -]', 'Введите правильное имя.', 'invalid')], verbose_name='Тег'),
        ),
    ]
