# Generated by Django 4.2.4 on 2023-08-17 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\Z', 'Введите правильный юзернейм.', 'invalid')], verbose_name='Уникальный юзернейм'),
        ),
    ]
